---
- hosts: myserver
  tasks:
    - name: create wordpress network
      community.docker.docker_network:
        name: wordpress
    - name: create wordpress container
      community.docker.docker_container:
        name: wordpress_container_4
        image: wordpress:latest
        networks:
          - name: wordpress
        ports: 
          - "6000:6000"

        env:
          WORDPRESS_DB_HOST: "db"
          WORDPRESS_DB_USER: "maurice"
          WORDPRESS_DB_PASSWORD: "127.0.0.1"
          WORDPRESS_DB_NAME: "wordpress_db"

        restart_policy: always  

    - name: Deploy MYSQL
      community.docker.docker_container:
        name: db
        image: mysql:5.7
        networks: 
          - name: wordpress
        volumes:
          - db:/var/lib/mysql
        env:
          MYSQL_DATABASE: "wordpress-db"        
          MYSQL_USER: "maurice"
          MYSQL_PASSWORD: "127.0.0.1"
          MYSQL_RANDOM_ROOT_PASSWORD: "1"
          
        restart_policy: always
    